'''print('digite as notas do primeiro bimestre')  #título co código
B1 = float(input())
print('digite a nota do segundo bimestre')  #criando uma variavél que vai solicitar o usuário a digitar o número. O comando int é para forçar o título de dados a ser inteiro
B2 = float(input())
print('digite a nota do terceiro bimestre')
B3 = float(input())
print('digite a nota do quarto bimestre')
B4 = float(input())
media = (B1 + B2 + B3 + B4) / 4
print('a media do aluno é ', media) '''

# código para o úsuario inserir dois nº e retornar todas as operações básicas e o módulo

print('mulheres tech copacabana')

print('digite o primeiro nº')
N1 = int(input())

print('digite o segundo nº')
N2 = int(input())

soma = N1 + N2
subtracao = N1 - N2
Multiplicacao = N1 * N2
divisao = N1 / N2
modulo = N1 % N2

print('A soma dos numeros é:',soma)
print('A subtração dos numeros é: ' , subtracao)
print ('A multiplicacao dos muneros é: ', Multiplicacao)
print('A divisao dos numeros é: ', divisao)
print('O modulo dos numeros é: ', modulo)
